// Automatically generated by astro-icon
// 2916c0c018fcfe467792112641dff17a4964c5f23f35f6ec1f3a534bdbe79ab7

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow_drawn"
		| "arrow_right"
		| "chain";
}